### ISSUE TITLE
Remove the unnecessary text at the bottom of the page.

### ISSUE THREAD

**Issue by advaithreddy** [advaithreddy/My_portfolio#1]
There is Some unwanted text at the bottom of the Page it is making the site look unprofessional
Please Remove it.

**Comment by dump501** [comment]
hello @advaithreddy on whiwh page the text is located ?

**Comment by advaithreddy** [comment]
The home page index.html @dump501

**Comment by dump501** [comment]
for removing the text before the footer right ? it will be a pleasure for me to take this task as my first contribution

**Comment by advaithreddy** [comment]
Great than set up a branch and send the pull request

**Comment by dump501** [comment]
okay !

**Comment by dump501** [comment]
`git push -u origin fix/remove_text`
ERROR: Permission to advaithreddy/My_portfolio.git denied to dump501.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

please this is what I get when trying to push what I did

**Comment by dump501** [comment]
I've created the `fix/remove_text` branch, update `index.html` and commit the changes

**Comment by advaithreddy** [comment]
Did you fork the repo mate
you can make changes in their forked repository and then submit pull requests. I will review the changes and decide whether to merge them.

**Comment by dump501** [comment]
Sorry I didn't fork the repo
